apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: siteconfig
    app.kubernetes.io/managed-by: kustomize
  name: webhook-service
  namespace: system
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: siteconfig-webhook-server-cert  
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: controller-manager
